### ISSUE TITLE
as of yesterday hunting was spawning animals normally today 6/18 there is 0 animals 

### ISSUE THREAD

**Issue by mudkip4487** [fkk-cz/noire-public#1341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no animals are spawning anymore and when i call anywhere it says no animals drive around no animals spawning at all.

### Expected Behavior

animals spawn when you go over there as soon as you get there you'll see em around.

### Steps To Reproduce

1. go to hunting 
2. see no animals 
3. do another job

### Anything else?

love this job don't know if im just doing something wrong or what but if it's broken im sad :{

**Comment by fkk-cz** [comment]
Hunting was changed to use networked animal peds instead of locally created peds, there is now a maximum of three animals that can spawn in the zone at a given time. In other words, peds are now 'shared' between players and can be killed/harvested by others in the zone.

Are you getting the message that no animals are available when using the whistle?

**Comment by JakeBurns23** [comment]
Im also getting the no animals in area no matter how much i explore even now im the only person here and been here hunting for a half hour and havent harvested a animal at all...

**Comment by mudkip4487** [comment]
> Im also getting the no animals in area no matter how much i explore even now im the only person here and been here hunting for a half hour and havent harvested a animal at all...
yeah left cause was searching for a minute and i know the main spots that i'd think they'd be but still nothing

**Comment by Ell34** [comment]
Hunting just needs an entire rework imo. The old hunting system was way better. That used to be my main legal.

**Comment by fkk-cz** [comment]
Looks like the spawned positions wasn't being reset when the ped was removed. Fixed in https://github.com/fkk-cz/noire/commit/d6483519a1ba3032089a589dbec57d0e69ec80d8.

**Comment by JakeBurns23** [comment]
New issue when the animal peds are clumsy they often fall to their own death by pathing and then cant be harvested because you didnt kill them and the body wont despawn so it wont spawn new animals. At hunting having this issue

**Comment by fkk-cz** [comment]
Yes, this was an old unneeded check to prevent people from killing each other's animals, this can be removed now. Probably should disable friendly fire to prevent people from (un)intentionally killing others with the hunting rifle as well.

**Comment by mudkip4487** [comment]
there's still an issue I think when an animal isn't harvested it sits there and the one that will replace it doesn't spawn
